---
- name: Keep only secure services
  routeros_command:
       commands:
         - /ip service disable {{ services_to_disable }}
- name: Change frequently used default ports
  routeros_command:
       commands:
         - /ip service set winbox port={{ winbox_access_port }}
         - /ip service set winbox address={{ winbox_access_network }}
- name: verify the changes
  routeros_command:
         commands:
           - /ip service print
  register: verify
  tags: verify
- debug: var=verify.stdout_lines
  tags: verify
