---
- name: verify results
  routeros_command:
          commands:
             - /interface print
             - /ip neighbor print
             - /ip service print
             - /user print
  register: verify
- debug: var=verify.stdout_lines
