---
- hosts: routers
  gather_facts: no
  tasks:
   - name: verify results
     routeros_command:
          commands:
             - /interface print
             - /ip neighbor print
             - /ip service print
     register: verify
   - debug: var=verify.stdout_lines
...
